export const eventInfo = {
  name: "Drama Arena 5101",
  subtitle: "Five a Hundred One",
  motto: "Nyalakan Api Kebersamaan, Wujudkan Idealisme Kehidupan",
  date: "Selasa, 18 Dzulqa'dah 1447H / 05 Mei 2026M",
  time: "Pukul 19.15 s.d. selesai",
  venue: "Depan Gedung Laboratorium KMI",
  period: "1447-1448 / 2026-2027",
  organizer: "Siswa Kelas 5 KMI Pondok Modern Darussalam Gontor",
  picInCharge: "Al-Ustadz Ahmad Nur Fajar Dwi Prakosa",
  publisher: "Darussalam Press, Pondok Modern Darussalam Gontor",
};

export const logoPhilosophy = [
  {
    title: 'Tulisan "D"',
    desc: 'Mengambil dari kata "Drama"',
    icon: "D",
  },
  {
    title: 'Tulisan "A"',
    desc: 'Mengambil dari kata "Arena"',
    icon: "A",
  },
  {
    title: "4 Sisi Garis",
    desc: "Melambangkan Moto Pondok Modern Darussalam Gontor: Berbudi tinggi, berbadan sehat, berpengetahuan luas, dan berpikiran bebas.",
    icon: "◇",
  },
  {
    title: "4 Sisi Berbentuk Kotak",
    desc: "Melambangkan lingkup persatuan dan kebersamaan, yaitu dengan menyatukan perbedaan dalam bingkai yang sama.",
    icon: "□",
  },
  {
    title: "5 Titik",
    desc: "Melambangkan Panca Jiwa Pondok Modern Darussalam Gontor: Keikhlasan, kesederhanaan, berdikari, Ukhuwah Islamiyah, dan kebebasan.",
    icon: "✦",
  },
  {
    title: "Cahaya (An-Nur)",
    desc: "Seperti lampu kecil yang menyala dalam kegelapan, kelas 5 dituntut tidak hanya menyimpan cahaya bagi dirinya, tetapi juga menyalakan cahaya di sekelilingnya.",
    icon: "☀",
  },
];

export const eventObjectives = [
  "Mengungkapkan rasa syukur kepada Allah SWT atas kenaikan kelas 5 KMI periode 1447-1448 / 2026-2027.",
  "Memperkenalkan kepada siswa-siswa baru bahwa kesenian di Pondok Modern Darussalam Gontor itu sangat beragam dan berbagai macam.",
  "Mendidik serta melatih siswa dalam bidang kepemimpinan, kemandirian, gotong royong, tanggung jawab, berpikir kritis, dan kerja keras.",
  "Mempererat tali Ukhuwah Islamiyyah antara para siswa Pondok Modern Darussalam Gontor.",
];

export const timeline = [
  { date: "06 Februari 2026", event: "Pembagian Proposal" },
  { date: "27 Februari 2026", event: "Pembacaan Struktur Panitia" },
  { date: "25 Maret 2026", event: "Pemilihan Ketua Panitia" },
  { date: "02 April 2026", event: "Awal Latihan DA" },
  { date: "14 April 2026", event: "Geladi 1 Drama Arena" },
  { date: "20 April 2026", event: "Geladi 2 Drama Arena" },
  { date: "01 Mei 2026", event: "Geladi 3 Drama Arena" },
  { date: "05 Mei 2026", event: "Geladi Suci Drama Arena" },
  { date: "07 Mei 2026", event: "It's Time to Shine for Drama Arena 5101! ✦" },
];

export const judges = [
  {
    no: "01",
    category: "Konsep Umum",
    members: ["Al-Ustadz Afique Rahmadiansyah, S.EI., M.Med.Kom.", "Al-Ustadz H. Husni Dzahaby, Lc."],
  },
  {
    no: "02",
    category: "Kategori Seni Musik & Suara",
    members: ["Al-Ustadz Hasan Muttaqin, S.Th.I., M.Pd.", "Al-Ustadz Rafi Kalima Gunaryanto"],
  },
  {
    no: "03",
    category: "Kategori Seni Tari & Atraksi",
    members: ["Al-Ustadz Mohammad Naufal Ash-shodiqi", "Al-Ustadz Muhammad Fakhri As Syujai"],
  },
  {
    no: "04",
    category: "Kategori Seni Theater",
    members: ["Al-Ustadz Dr. Hasib Amrullah, S.Ag., M.Ud.", "Al-Ustadz Winka Ghozi Nafi', S.H."],
  },
  {
    no: "05",
    category: "Kategori Seni Bahasa",
    members: ["Al-Ustadz Muhammad Fauzan", "Al-Ustadz Fariz Istiqlal Harahap, S.I.Kom."],
  },
];

export const performances = [
  {
    id: 1,
    order: 1,
    name: "Senandung Sholawat",
    duration: "7 Menit",
    category: "Seni Musik & Suara",
    participants: 30,
    supervisors: ["Al-Ustadz Syirajuddin", "Al-Ustadz Ayus Sofi"],
    description: "Sholawat indah nan syahdu diiringi dengan iringan musik hadroh yang akan membawakan sholawat-sholawat indah kepada hadirin sebagai tanda atas keberkahan dan nilai islami acara Drama Arena 5101.",
    emoji: "🎵",
    color: "#FF6B00",
  },
  {
    id: 2,
    order: 2,
    name: 'Band 5101: "Lomba Sihir!"',
    duration: "4 Menit",
    category: "Seni Musik & Suara",
    participants: 8,
    supervisors: ["Al-Ustadz M. Haidar Al-Wa'ie", "Al-Ustadz Agata Daniswara", "Al-Ustadz Muhammad Amin Firdaus"],
    description: 'Band Drama Arena 5101 yang akan membawakan lagu penyemangat band Lomba Sihir yang berjudul "Lomba Sihir!"',
    emoji: "🎸",
    color: "#e85d04",
  },
  {
    id: 3,
    order: 3,
    name: "Master of Ceremony",
    duration: "10 Menit",
    category: "Seni Bahasa & Literasi",
    participants: 2,
    supervisors: ["Al-Ustadz M. Nurul Faizin", "Al-Ustadz Ade Rezki Agesta"],
    description: "Pembawa acara yang akan membuka acara Drama Arena dengan menggunakan 3 bahasa yang memukau!",
    emoji: "🎤",
    color: "#FF6B00",
  },
  {
    id: 4,
    order: 4,
    name: "Tilawah Ayat Suci Al-Qur'an",
    duration: "7 Menit",
    category: "Seni Musik & Suara",
    participants: 2,
    supervisors: ["Al-Ustadz Nashrul Haq"],
    description: "Lantunan ayat suci Allah yang akan mengawali acara, memohon keberkahan dan kelancaran kepada Allah SWT. Qori' akan membacakan Qur'an Surah Ali 'Imran ayat 133-136.",
    emoji: "📖",
    color: "#cc4400",
  },
  {
    id: 5,
    order: 5,
    name: "Sambutan Ketua Drama Arena",
    duration: "7 Menit",
    category: "Seni Bahasa & Literasi",
    participants: 3,
    supervisors: ["Al-Ustadz M. Nurul Faizin", "Al-Ustadz Ade Rezki Agesta"],
    description: "Sambutan dari ketua Drama Arena 5101",
    emoji: "🎙️",
    color: "#FF6B00",
  },
  {
    id: 6,
    order: 6,
    name: "Grand Opening: OST DA 5101",
    duration: "7 Menit",
    category: "Seni Musik & Suara",
    participants: 2,
    supervisors: ["Al-Ustadz Abdul Rosyid", "Al-Ustadz M. Rifqi Fachriyan"],
    description: "Grand Opening Drama Arena 5101 yang akan diiringi dengan OST Drama Arena 5101.",
    emoji: "🌟",
    color: "#e85d04",
  },
  {
    id: 7,
    order: 7,
    name: "Drama POV 1 = Bintang",
    duration: "10 Menit",
    category: "Seni Theater",
    participants: 10,
    supervisors: ["Al-Ustadz M. Radja Althafa", "Al-Ustadz Ade Rezki Agesta"],
    description: "Penampilan drama yang menceritakan kehidupan seorang ketua rayon yang menjadi midola para anggotanya, ia adalah Bintang.",
    emoji: "⭐",
    color: "#FF6B00",
  },
  {
    id: 8,
    order: 8,
    name: "Choir 5101",
    duration: "10 Menit",
    category: "Seni Musik & Suara",
    participants: 43,
    supervisors: ["Al-Ustadz Moh. Yusuf Ubaidillah", "Al-Ustadz M. Haidar Al-Wa'ie", "Al-Ustadz Muhammad Avisena"],
    description: "Paduan suara 5101 yang akan membawakan tiga lagu syahdu sekaligus.",
    emoji: "🎶",
    color: "#cc4400",
  },
  {
    id: 9,
    order: 9,
    name: 'Nasyid 5101: "Syukur Alhamdulillah"',
    duration: "4 Menit",
    category: "Seni Musik & Suara",
    participants: 6,
    supervisors: ["Al-Ustadz Andika Rizaldi"],
    description: "Nasyid syahdu yang akan membawakan lagu untuk mengajak kita mensyukuri segala nikmat yang telah diberikan oleh Allah SWT.",
    emoji: "🤲",
    color: "#FF6B00",
  },
  {
    id: 10,
    order: 10,
    name: "Drama POV 2 = Azka",
    duration: "10 Menit",
    category: "Seni Theater",
    participants: 15,
    supervisors: ["Al-Ustadz M. Radja Althafa", "Al-Ustadz Ade Rezki Agesta"],
    description: "Drama berpindah fokus ke aggonta rayon GBSK. Bagaimanakah kelah kesuh mereka menjadi anggota rayon? Apakah mereka hidup dalam rayon yang 'Maskani Jannati'? Ataukah... sebaliknya?",
    emoji: "🎭",
    color: "#e85d04",
  },
  {
    id: 11,
    order: 11,
    name: "Ya Maulay Ya Maulay",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 23,
    supervisors: ["Al-Ustadz Ahmad Ridwan", "Al-Ustadz Sayid Wildan Al Jannatan"],
    description: "Pertunjukkan suatu tari tradisional Melayu, khususnya populer di Riau, yang berakar dari kebudayaan Arab dan Melayu. Tari ini sarat nilai filosofis-religius dan sering dipentaskan sebagai media da'wah serta hiburan.",
    emoji: "🌙",
    color: "#FF6B00",
  },
  {
    id: 12,
    order: 12,
    name: "Black Mask Rhythm",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 19,
    supervisors: ["Al-Ustadz Agata Daniswara", "Al-Ustadz Ibrahim Hidayatullah"],
    description: "Black Mask Rhtyhm (Topeng Ireng) adalah suatu tarian tradisional berasal dari desa Tuk Songo Borobudur dan berkembang pesat di Kab. Magelang, Jawa Tengah.",
    emoji: "🎭",
    color: "#cc4400",
  },
  {
    id: 13,
    order: 13,
    name: "Udal Adul Well",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 18,
    supervisors: ["Al-Ustadz M. Rafli Hidayat", "Al-Ustadz Moh. Razka Al-Isfahany"],
    description: "Pertunjukkan kesenian tradisional khas Jawa Barat, khususnya dari Kab. Subang, yang menampilkan boneka singa yang diusung oleh 4 orang penari sekaligus.",
    emoji: "🦁",
    color: "#FF6B00",
  },
  {
    id: 14,
    order: 14,
    name: "SKA N DUT",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 26,
    supervisors: ["Al-Ustadz Fatahna Fathan Mubina", "Al-Ustadz Agata Daniswara", "Al-Ustadz Andika Rizaldi"],
    description: "Pementasan tari asyik khas Jawa yang memadukan alat musik tradisional dengan instrumen modern seperti keyboard, gitar, dan ukulele.",
    emoji: "🎵",
    color: "#e85d04",
  },
  {
    id: 15,
    order: 15,
    name: "Drama POV 3 = Mudabbir",
    duration: "10 Menit",
    category: "Seni Theater",
    participants: 10,
    supervisors: ["Al-Ustadz M. Radja Althafa", "Al-Ustadz Ade Rezki Agesta"],
    description: "Kali ini kehidupan rayon dibuat tegang, dengan peralihan fokus drama ke kumpul wajib para mudabbir rayon GBSK. Bagaimanakah kelangsungan kumpul tersebut?",
    emoji: "🎬",
    color: "#FF6B00",
  },
  {
    id: 16,
    order: 16,
    name: 'Puisi 5101: "Antara Uswah dan Amanah"',
    duration: "15 Menit",
    category: "Seni Theater",
    participants: 7,
    supervisors: ["Al-Ustadz Muhammad Nurul Faizin"],
    description: "Puisi sebagai lanjutan Drama POV 3 = Mudabbir yang akan membawakan 2 kata mulia: Uswah dan Hasanah, sebagai landasan dasar 'kemudabbiran' Pondok Modern Darussalam Gontor.",
    emoji: "📜",
    color: "#cc4400",
  },
  {
    id: 17,
    order: 17,
    name: 'Band 5101: "Tangguh"',
    duration: "10 Menit",
    category: "Seni Musik & Suara",
    participants: 7,
    supervisors: ["Al-Ustadz M. Haidar Al-Wa'ie", "Al-Ustadz Agata Daniswara", "Al-Ustadz M. Amin Firdaus"],
    description: 'Penampilan musikal oleh Band Drama Arena 5101 yang akan membawakan lagu berjudul "Tangguh".',
    emoji: "🎸",
    color: "#FF6B00",
  },
  {
    id: 18,
    order: 18,
    name: "Tari Ratoeh Jaroe",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 7,
    supervisors: ["Al-Ustadz Febri Fitrah Muliawan", "Al-Ustadz Ahmad Ridwan"],
    description: "Tari Ratoeh Jaroe merupakan tarian tradisonal Aceh dengan gerakan cepat, kompak, dinamis, dan energik.",
    emoji: "💫",
    color: "#e85d04",
  },
  {
    id: 19,
    order: 19,
    name: "Infinity Beatbox",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 17,
    supervisors: ["Al-Ustadz Hammad Fida Rahman", "Al-Ustadz Muhammad Zidan Fadlullah"],
    description: "Penampilan tari semi barat yang ditampilkan oleh santri dengan iringan musik yang dimainkan menggunakan mulut atau yang dikenal dengan beatbox.",
    emoji: "🎤",
    color: "#FF6B00",
  },
  {
    id: 20,
    order: 20,
    name: "Le Le Re Dance",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 16,
    supervisors: ["Al-Ustadz Abdillah Malik Fauzan Abrori"],
    description: "Le le re dance atau yang lebih dikenal dengan tari India adalah bentuk seni kino yang menggabungkan antara spiritual, ritme, dan cerita, berakar dari teks suci Natya Shastra.",
    emoji: "💃",
    color: "#cc4400",
  },
  {
    id: 21,
    order: 21,
    name: "Band 5101: Medley Tongkrongan",
    duration: "5 Menit",
    category: "Seni Musik",
    participants: 4,
    supervisors: ["Al-Ustadz Muhammad Haidar Al-Wa'ie", "Al-Ustadz Muhammad Amin Firdaus", "Al-Ustadz Agata Daniswara"],
    description: 'Band Drama Arena 5101 yang akan membawakan lagu dengan judul "Tongkrongan".',
    emoji: "🎵",
    color: "#FF6B00",
  },
  {
    id: 22,
    order: 22,
    name: "Drama POV 4 = Atlan",
    duration: "10 Menit",
    category: "Seni Theater",
    participants: 15,
    supervisors: ["Al-Ustadz Radja Althafa", "Al-Ustadz Ade Rezki Agesta"],
    description: "Di scene kali ini akan menjelaskan tentang kehidupan santri kelas lima, melainkan mereka bukanlah mudabbir... siapakah mereka...?? yaps, mereka adalah ATLAN.",
    emoji: "🎭",
    color: "#e85d04",
  },
  {
    id: 23,
    order: 23,
    name: "Raqs Arabian",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 20,
    supervisors: ["Al-Ustadz Hazel Hudaya Bisri", "Al-Ustadz Reynaldi Alvian"],
    description: "Raqs Arabian atau yang dikenal dengan tari Arab merupakan tarian tradisional yang berasal dari Timur Tengah dengan sejarah yang cukup panjang meliputi tari perut (raqs sharqi), Dabke, dan Ardah.",
    emoji: "🌹",
    color: "#FF6B00",
  },
  {
    id: 24,
    order: 24,
    name: "Art of Balance",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 16,
    supervisors: ["Al-Ustadz Tsabitul Hidayat"],
    description: "Penampilan atraksi yang menggunakan alat juggling tradisional berasal dari Cina atau yang sering disebut dengan Diabolo. Alat ini dimainkan dengan cara memutar cepat bola atau (yoyo) dengan talinya.",
    emoji: "⚖️",
    color: "#cc4400",
  },
  {
    id: 25,
    order: 25,
    name: "Hikaru Toki DA",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 43,
    supervisors: ["Al-Ustadz Krisna Achmad Pasya", "Al-Ustadz Muhammad Rifqi Fachriyan"],
    description: "Pertunjukan tari modern ala Jepang (Wotagei) yang identik menggunakan tongkat bercahaya (lightstick) dan gerakan khusus seperti romansu atau thunder snake.",
    emoji: "✨",
    color: "#FF6B00",
  },
  {
    id: 26,
    order: 26,
    name: "Tong Basudara",
    duration: "4 Menit",
    category: "Seni Tari & Atraksi",
    participants: 25,
    supervisors: ["Al-Ustadz Affan Mahatma Wuran"],
    description: "Pementasan tari asyik khas Jawa yang memadukan alat musik tradisional dengan instrumen modern seperti keyboard, gitar, dan ukulele.",
    emoji: "🥁",
    color: "#e85d04",
  },
  {
    id: 27,
    order: 27,
    name: "Drama POV 5 = Pijar",
    duration: "10 Menit",
    category: "Seni Theater",
    participants: 15,
    supervisors: ["Al-Ustadz M. Radja Althafa", "Al-Ustadz Ade Rezki Agesta"],
    description: "Drama berpindah fokus ke aggonta rayon GBSK. Bagaimanakah kelah kesuh mereka menjadi anggota rayon? Apakah mereka hidup dalam rayon yang 'Maskani Jannati'? Ataukah... sebaliknya?",
    emoji: "🔥",
    color: "#FF6B00",
  },
  {
    id: 28,
    order: 28,
    name: 'Grand Closing: "Api Perjuangan"',
    duration: "5 Menit",
    category: "Seni Musik & Suara",
    participants: -1, // All students
    supervisors: ["Al-Ustadz M. Radja Althafa"],
    description: 'Nafas terakhir Drama Arena 5101 yang ditandai dengan menyanyikan lagu "Api Perjuangan" dengan khidmat.',
    emoji: "🏆",
    color: "#cc4400",
  },
];

export const categories = [
  {
    name: "Seni Musik & Suara",
    items: ["Senandung Sholawat", "Tilawah Ayat Suci Al-Qur'an", "Band 5101", "Choir 5101", "Nasyid 5101"],
    icon: "🎵",
  },
  {
    name: "Seni Tari & Atraksi",
    items: ["Ya Maulay Ya Maulay", "Black Mask Rhythm", "Tong Basudara", "Udal Adul Wel", "SKA N Dut", "Tari Ratoeh Jaroe", "Raqs Arabian", "HikaruToki DA", "Le Le Re Dance", "Infinity Beatbox", "Art of Balance"],
    icon: "💃",
  },
  {
    name: "Seni Theater",
    items: ["Drama POV 1-5", "Puisi 5101"],
    icon: "🎭",
  },
  {
    name: "Seni Bahasa & Literasi",
    items: ["Master of Ceremony", "Sambutan Ketua Drama Arena", "Puisi 5101"],
    icon: "📖",
  },
];

export const choirs = [
  { title: "Mars Darussalam", desc: "Lagu kebanggaan Pondok Modern Darussalam Gontor" },
  { title: "Spontan (uhuy)", desc: "Lagu ceria tentang kehidupan di Darussalam" },
  { title: "Ini Abadi", desc: "Lagu tentang kenangan yang tak terlupakan" },
];
